apiVersion: apps/v1
kind: Deployment
metadata:
  name: sxb-static-backgroundtask
  namespace: sxb
  labels:
    app: sxb-static-backgroundtask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sxb-static-backgroundtask
  template:
    metadata:
      labels:
        app: sxb-static-backgroundtask
    spec:
    
      containers:
      - name: sxb-static-backgroundtask
        image: "registry.cn-shenzhen.aliyuncs.com/sxkid/sxb-static-backgroundtask"
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      terminationGracePeriodSeconds: 10
      restartPolicy: Always